Added back 1.12 recipes for Applied Energistics 2
mekanism/Mekanism pull request #6508
Opened 2020-08-26 20:42 UTC by shartte

Fixes #6479

For the record: Not a fan of the recipes that directly convert crystals and dusts into their purified variants.
The recipes that do this for seeds I find less offensive (although the energy requirement might be tweaked if your recipes support it), since it's similar to the good 'ol AE2Stuff crystal grower.

One implementation note: AE2 now exposes the API only in common startup since it's not thread-safe to do so in the Mod constructor. Since this is datagen, common setup never runs, so the public-facing API is never made available. That's the reasoning for grabbing the API instance from the internal class here, which is slightly less stable.
We are however not going to change the item IDs in 1.16.1 anymore anyway.

2020-08-28 09:10 UTC, shartte commented
p.s. @pupnewfster Do you have brine as a fluid? Might be more sensible to infuse a crystal with brine to get a purified crystal if you do

2020-09-06 09:43 UTC, thiakil requested changes

2020-09-06 09:43 UTC, thiakil commented on src/datagen/main/java/mekanism/common/recipe/compat/AE2RecipeProvider.java
> +                .build(consumer, Mekanism.rl(basePath + "certus_ore_to_dust"));
bad name - dust != crystal

2020-09-06 09:43 UTC, thiakil commented on src/datagen/main/java/mekanism/common/recipe/compat/AE2RecipeProvider.java
> +                .build(consumer, Mekanism.rl(basePath + "charged_certus_ore_to_dust"));
bad name - dust != crystal

2020-09-06 09:44 UTC, thiakil commented
> Not a fan of the recipes that directly convert crystals and dusts into their purified variants.

It doesn't double it, so while it may not be particularly _useful_ it shouldn't break balancing?

2020-09-06 10:30 UTC, shartte commented
> > Not a fan of the recipes that directly convert crystals and dusts into their purified variants.
> 
> It doesn't double it, so while it may not be particularly _useful_ it shouldn't break balancing?

It's that pure crystals are **required** for higher-level recipes. This either forces people to manually grow them, or figure out an automation setup, which is not trivial. If they can produce them by dumping them into an easy-to-automate Mekanism machine however, that trivializes that part of the content.

The doubling part is not really troubling to me, I mean the ores give 5 crystals each already :D

2020-09-06 10:34 UTC, shartte commented on src/datagen/main/java/mekanism/common/recipe/compat/AE2RecipeProvider.java
> +                .build(consumer, Mekanism.rl(basePath + "certus_ore_to_dust"));
Fixed. Copypasta :-|

2020-09-06 10:34 UTC, shartte commented on src/datagen/main/java/mekanism/common/recipe/compat/AE2RecipeProvider.java
> +                .build(consumer, Mekanism.rl(basePath + "charged_certus_ore_to_dust"));
Fixed. Copypasta :-|

2020-09-06 11:04 UTC, thiakil commented
> If they can produce them by dumping them into an easy-to-automate Mekanism machine however, that trivializes that part of the content.

It's already pretty trivial imo. It's just a trade-off between amount of ore/crystals you throw at it vs more grindy automation.

Also, you could have just left those recipes out and made us add them if we really wanted them (I'm not terribly fussed, though the crystal purification has always seemed unnecessarily grindy in base AE2)

> Don't you have some form of brine fluid that you could make it consume and use the machines with fluid enrichment instead?

Yes, though it would just be a different grindy way as brine isn't super simple to get going

2020-09-06 12:03 UTC, shartte commented
@thiakil I think we may have different definitions of grindy. To automate crystals in AE2 you need to understand what a subnet is and actually understand how formation/annihilation planes work.

I would have left them out, but when talking to @pupnewfster, he wanted me to restore the old recipes.

2020-09-24 13:17 UTC, pupnewfster commented
If you could update this to 1.16.3 (it seems that alphas are also now being mirrored https://modmaven.k-4u.nl/appeng/appliedenergistics2/8.1.0-alpha.3/) I will go ahead and merge it (otherwise I will probably do so myself sometime before releasing 10.0.10). Also if you two think that a couple recipes should be removed feel free to do so, I mainly said for now just port them all as I don't know what the majority of them are and it is easier to remove than have to relook them up.

2020-09-24 18:51 UTC, shartte commented
Rebased & Squashed

2020-09-24 19:09 UTC, merged