Fixed getCapacity computer methods for pipes, tubes, cables to get tr…
mekanism/Mekanism pull request #7367
Opened 2021-12-23 06:18 UTC by toddlersizedsharkcage

…ansmitter network capacity instead of transmitter capacity.

Validated changes by checking values of each method returned by CC computer in game.

2021-12-23 07:31 UTC, toddlersizedsharkcage commented
Results with fixed methods:

ultimateMechanicalPipe
getNeeded 128000
getFilledPercentage 0.75
getBuffer {
  name = "minecraft:water",
  amount = 384000,
}
getCapacity 512000


ultimateUniversalCable
getNeeded 8192000
getFilledPercentage 0.75
getBuffer 24576000
getCapacity 32768000


ultimatePressurizedTube
getNeeded 1024000
getFilledPercentage 0.75
getBuffer {
  name = "mekanism:sulfuric_acid",
  amount = 3072000,
}
getCapacity 4096000

2021-12-23 14:21 UTC, pupnewfster requested changes

2021-12-23 14:21 UTC, pupnewfster commented on src/main/java/mekanism/common/tile/transmitter/TileEntityMechanicalPipe.java
> +        return getTransmitter().getTransmitterNetwork().getCapacity();
Strictly speaking I think each of these should probably be like:
```java
MechanicalPipe pipe = getTransmitter();
return pipe.hasTransmitterNetwork() ? pipe.getTransmitterNetwork().getCapacity() : pipe.getCapacity();
```

2021-12-23 23:58 UTC, toddlersizedsharkcage reviewed
Updated with requested changes

2021-12-24 00:00 UTC, pupnewfster approved these changes

2021-12-24 00:12 UTC, merged