Move Personal Storage Item Inventory to World Saved Data
mekanism/Mekanism pull request #7867
Opened 2023-09-17 04:40 UTC by thiakil

## Changes proposed in this pull request:

- Instead of being on the itemstack, the inv is stored in world saved data, one file per owner uuid
- Stack only has the Security/owner info and an inv UUID
- Refactors `ISustainedInventory` a little to avoid accidental misuse and slightly redundant varargs
- Removed some no longer needed fallbacks from loot generation (9d53c3a8ee80ab8a5542e0b4798b1569fbfa4ad3)
- Added ability for Inventory Attribute to specify a custom loot generation
- Old saved item inventories will be converted when they're opened or placed
- Item GUIs will now ensure that the hand that opened it still contains the item (#7855 though the dupe is resolved by the move to saved data)

## Breaking(-ish) changes
- Clone/pick block will no longer contain a copy of the inventory (so WAILA/TOP doesn't cause an explosion in the saved data size)

2023-09-17 15:02 UTC, pupnewfster requested changes

2023-09-17 15:02 UTC, pupnewfster commented on src/api/java/mekanism/api/NBTConstants.java
> +    public static final String PERSONAL_STORAGE_ID = "personalStorageId";
We should add a since javadoc on this field

2023-09-17 15:02 UTC, pupnewfster commented on src/main/java/mekanism/common/block/attribute/Attributes.java
> +        public AttributeInventory(BiFunction<T, CopyNbtFunction.Builder, @NotNull Boolean> customLootBuilder) {
This parameter and the field should probably both have nullable annotations

2023-09-17 15:02 UTC, pupnewfster commented on src/main/java/mekanism/common/block/attribute/Attributes.java
> +        public BiFunction<T, CopyNbtFunction.Builder, Boolean> getCustomLootBuilder() {
Is there a use case for this returning the `BiFunction` rather than just being a boolean method that accepts the params and passes them to the `BiFunction`?

2023-09-17 15:02 UTC, pupnewfster commented on src/main/java/mekanism/common/item/loot/PersonalStorageContentsLootFunction.java
> +    public static class Serialiser implements Serializer<PersonalStorageContentsLootFunction> {
Given the rest of the codebase is american english this should be `Serializer` rather than `Serialiser`. Or if the reason this is named the way it is so that the implementation doesn't need to be a FQN then maybe `PersonalStorageSerializer`

2023-09-17 15:02 UTC, pupnewfster commented on src/main/java/mekanism/common/registries/MekanismContainerTypes.java
> +    public static final ContainerTypeRegistryObject<PersonalStorageItemContainer> PERSONAL_STORAGE_ITEM = CONTAINER_TYPES.register("personal_storage_item", () -> MekanismItemContainerType.item(ItemBl
What is the reason behind changing this line? As I believe the previous variant is just a helper for what this is now doing?

2023-09-17 15:02 UTC, pupnewfster commented on src/main/java/mekanism/common/lib/inventory/personalstorage/PersonalStorageData.java
> +        ListTag entries = nbt.getList("data", Tag.TAG_COMPOUND);
`NBTConstants.DATA`

2023-09-17 15:02 UTC, pupnewfster commented on src/main/java/mekanism/common/lib/inventory/personalstorage/PersonalStorageData.java
> +        pCompoundTag.put("data", entries);
`NBTConstants.DATA`

2023-09-17 15:02 UTC, pupnewfster commented on src/main/java/mekanism/common/lib/inventory/personalstorage/PersonalStorageData.java
> +    public CompoundTag save(CompoundTag pCompoundTag) {
Remove the `p` from the parameter name

2023-09-17 15:02 UTC, pupnewfster commented on src/main/java/mekanism/common/lib/inventory/personalstorage/PersonalStorageData.java
> +            inventoriesById.put(entry.getUUID("uuid"), inv);
These should use `NBTConstants`, whether it is using `ITEMS` and `INVENTORY_ID` or whether we add two more for this. (Likewise the saving then should use the same constants as are used here)

2023-09-17 15:02 UTC, pupnewfster commented on src/main/java/mekanism/common/item/loot/PersonalStorageContentsLootFunction.java
> +    private static final Set<LootContextParam<?>> REFERENCED_PARAMS = ImmutableSet.of(LootContextParams.BLOCK_ENTITY);
Rather than doing `ImmutableSet.of` we may as well use the builtin java variant `Set.of`

2023-09-17 15:02 UTC, pupnewfster commented on src/main/java/mekanism/common/item/loot/PersonalStorageContentsLootFunction.java
> +            //only save if its empty
I believe this comment is meant to say `only save if it's not empty`

2023-09-17 15:02 UTC, pupnewfster commented on src/main/java/mekanism/common/item/block/ItemBlockPersonalStorage.java
> +public class ItemBlockPersonalStorage<BLOCK extends BlockPersonalStorage<?,?>> extends ItemBlockTooltip<BLOCK> implements IGuiItem {
Why does this no longer implement `IItemSustainedInventory`? One feature this now doesn't support is `InventoryUtils#dropItemContents`. Which yes potentially should be overridden so we only drop contents when the item is destroyed if it is public, but previously I had them drop them regardless just so that player's have more of a chance at their items not all getting destroyed (which I still think makes the most sense).

Additionally we probably want to override `onDestroyed(ItemEntity, DamageSource` so that when the stack is destroyed then we can clean up the WSD and make it not keep track of the contents for the stack anymore.

2023-09-17 15:02 UTC, pupnewfster commented on src/main/java/mekanism/common/lib/inventory/personalstorage/PersonalStorageManager.java
> +        ListTag legacyData = ItemDataUtils.getList(stack, NBTConstants.ITEMS);
Do we want a TODO to remove this at some point? Such as `//TODO - 1.21: Remove legacy loading`?

2023-09-19 11:51 UTC, thiakil commented on src/main/java/mekanism/common/registries/MekanismContainerTypes.java
> +    public static final ContainerTypeRegistryObject<PersonalStorageItemContainer> PERSONAL_STORAGE_ITEM = CONTAINER_TYPES.register("personal_storage_item", () -> MekanismItemContainerType.item(ItemBl
`IMekanismItemContainerFactory` vs `IMekanismSidedItemContainerFactory` - I copied what the QIO dashboard does

2023-09-19 12:07 UTC, thiakil commented on src/main/java/mekanism/common/item/block/ItemBlockPersonalStorage.java
> +public class ItemBlockPersonalStorage<BLOCK extends BlockPersonalStorage<?,?>> extends ItemBlockTooltip<BLOCK> implements IGuiItem {
Well it not longer satisfies the general contract of that interface as the itemstack itself doesn't contain the inventory. Key among it being that the Loot functions try to copy NBT data.

This kind of destroying thing came up on Discord when this was being discussed, I think it was in Neoforged, that if someone loses their personal chest / backpack, it's quite useful for an admin to be able to restore it. The rest of the world save size will always dwarf the lost space of one chest, even if it's full.

2023-09-19 14:20 UTC, pupnewfster commented on src/main/java/mekanism/common/registries/MekanismContainerTypes.java
> +    public static final ContainerTypeRegistryObject<PersonalStorageItemContainer> PERSONAL_STORAGE_ITEM = CONTAINER_TYPES.register("personal_storage_item", () -> MekanismItemContainerType.item(ItemBl
Ahh I misread which class the call was against.

2023-09-19 14:49 UTC, pupnewfster commented on src/main/java/mekanism/common/item/block/ItemBlockPersonalStorage.java
> +public class ItemBlockPersonalStorage<BLOCK extends BlockPersonalStorage<?,?>> extends ItemBlockTooltip<BLOCK> implements IGuiItem {
I still need to do a bit of testing relating to the commit I just made, but what are your thoughts on that as a midway solution?

2023-09-20 14:18 UTC, pupnewfster approved these changes

2023-09-20 14:30 UTC, merged