Blasting Highlight Event Visual Bug?
mekanism/Mekanism pull request #8240
Opened 2024-09-28 12:15 UTC by alegian

This is my first time trying to contribute something to someone else's repo, please be kind.

## Problem
I was looking at the `RenderHighlightEvent` code for the AoE blasting, and I noticed that you are calling recursive  `RenderHighlightEvent`s for each block affected, so that they may have a chance to cancel themselves. 

However, when creating those recursive events, you pass the original `rayTraceResult` as parameter. I believe this means that instead of simulating one event for each block in the AoE, you actually simulate the origin-block's event many times over.

## Changes proposed in this pull request:
Create a seperate `BlockHitResult` for each `blastingTarget` blockPos. For its parameters, I essentially cloned the original `BlockHitResult`, changing only the blockPos. So for example if the original block was 'hit' at the top left, every AoE block is going to simulate a top left hit aswell.

2024-10-24 16:39 UTC, pupnewfster requested changes
Thanks, and I am sorry for taking a while to get to reviewing this. Only a minor cleanup related comment.

2024-10-24 16:39 UTC, pupnewfster commented on src/main/java/mekanism/client/render/RenderTickHandler.java
> +                            BlockHitResult currResult = new BlockHitResult(rayTraceResult.getLocation(), rayTraceResult.getDirection(), blastingTarget, rayTraceResult.isInside());
I believe this can be `rayTraceResult.withPosition(blastingTarget)`. We can also jjust inline it in the call to `ClientHooks#onDrawHighlight` so that we don't have to construct the new object for if the position is already the blasting target.

2024-10-25 19:10 UTC, alegian commented on src/main/java/mekanism/client/render/RenderTickHandler.java
> +                            BlockHitResult currResult = new BlockHitResult(rayTraceResult.getLocation(), rayTraceResult.getDirection(), blastingTarget, rayTraceResult.isInside());
how did you know that helper exists 😮

2024-11-13 23:24 UTC, pupnewfster approved these changes

2024-11-13 23:25 UTC, merged