Adapt the "onAlloyIteraction" and "canUpgrade" methods to ITier
mekanism/Mekanism pull request #8252
Opened 2024-11-09 12:06 UTC by lostmyself8

## Changes proposed in this pull request:
1.When adding extra alloys, the "AlloyTier" accepted by "onAlloyIteraction" is too limited. It would be better to replace it with  a subclass of "ITier", at least I don't have to do repetitive work.
2.I modified the parameters in 'canUpgrade' to also adapt to subclasses of 'ITier', reducing unnecessary forced conversions.
3.Please forgive me for using a translator.
Thank you for everything you have done for mek.

2024-11-17 12:32 UTC, thiakil commented
Please remove the generic, it's not needed. Just `ITier` should be fine

2024-11-17 15:07 UTC, lostmyself8 commented
I changed them

2025-02-26 01:06 UTC, pupnewfster commented
I am a bit confused on the use case here. Is it to allow other items to be used as alloys as alternates for upgrading? Or is this for adding more tiers? Given with how the logic works it still ends up falling back to BaseTier which is also an enum so for more tiers that doesn't really help in terms of extending it.

2025-02-26 02:25 UTC, lostmyself8 commented
I have added more tiers, which belong to the new enumeration class. If you want to upgrade the pipeline with alloys, you cannot use AlloyTier anymore. Due to the addition of four new alloys (perhaps more in the future), I cannot directly use AlloyTier to bypass the restrictions, as AlloyTier only defines three tiers.

2025-02-26 07:00 UTC, thiakil commented
the point is that https://github.com/mekanism/Mekanism/blob/38b95729a41b9667694808859fd7ff336af8396e/src/main/java/mekanism/common/tile/transmitter/TileEntityTransmitter.java#L398

Takes the `BaseTier`, which is also an enum. So your PR doesnt fix anything meaningful

2025-02-28 07:43 UTC, lostmyself8 commented
I seem to have forgotten to modify this. Perhaps I need to add a special interface to BaseTier so that I can use this method through the interface.

Because I added an enum AdvanceTier similar to BaseTier, if they have a common interface, I don't need to write an upgradeResult and onExtraAlloyIteraction again.

2025-03-06 11:56 UTC, thiakil requested changes
`BaseTier` is still a problem with this, as mentioned in previous comments

2025-03-12 18:16 UTC, closed without merging

2025-03-12 18:19 UTC, pupnewfster commented
I believe I expanded things in a cleaner way that should handle your use case, please let me know if it does.