Add a warning for machine inactivity due to redstone control
mekanism/Mekanism pull request #8262
Opened 2024-11-22 14:18 UTC by bukowski912

- Make GuiInsetElement able to track warnings with a supplier
- Use a separate texture for GuiInsetElement on a warning condition
- Inject an activation supplier into the redstone control tab during its creation
- Write a corresponding lang entry for "en_us" (we will need to support more langs in future)

2024-11-22 19:22 UTC, pupnewfster requested changes

2024-11-22 19:22 UTC, pupnewfster commented on src/main/java/mekanism/client/gui/GuiMekanismTile.java
> +            addRenderableWidget(new GuiRedstoneControlTab(this, tile).warning(supplier));
This should probably be adjusted to just be:
```java
addRenderableWidget(new GuiRedstoneControlTab(this, tile).warning(WarningType.REDSTONE_UNACTIVATED, () -> !tile.isRedstoneActivated()));
```
and have the `warning` method be implemented similar to the one in `GuiSlot`

2024-11-22 19:22 UTC, pupnewfster commented on src/main/java/mekanism/client/gui/element/GuiInsetElement.java
> +    public void draw(@NotNull GuiGraphics guiGraphics) {
This can be protected

2024-11-22 19:22 UTC, pupnewfster commented on src/main/java/mekanism/client/gui/element/GuiInsetElement.java
> +            ResourceLocation texture = (left ? WARNING_LEFT : WARNING_RIGHT);
You can just inline the texture so it is `innerDraw(guiGraphics, left ? WARNING_LEFT : WARNING_RIGHT);`

2024-11-22 19:22 UTC, pupnewfster commented on src/datagen/generated/mekanism/assets/mekanism/lang/en_us.json
> +  "gui.mekanism.issues.redstone_unactivated": "Machine is currently inactive due to its redstone control setting.",
This should be added via datagen (MekanismLangProvider and then running `runData`) rather than being manually added to this file

2024-11-22 23:17 UTC, bukowski912 commented
Whups, I pushed a cache file. Is there a reason why it isn't in the `.gitignore`?

2024-11-22 23:53 UTC, bukowski912 commented
I hate GitHub mobile.

2024-11-23 00:56 UTC, pupnewfster commented
The cache file is so that you don't have to rewrite all the files to disk when you first checkout and run datagen.

2024-11-23 08:38 UTC, thiakil commented on src/datagen/main/java/mekanism/client/lang/MekanismLangProvider.java
> +        add(MekanismLang.ISSUE_REDSTONE_UNACTIVATED, " - Inactive because of the redstone control setting");
- I don't like the name. Something like `REDSTONE_PREVENTS_ACTIVATION`
- the text would be better as `Redstone conditions not met` or similar (the _setting_ is not the problem, the condition not being met is)

2024-11-23 09:05 UTC, bukowski912 commented on src/datagen/main/java/mekanism/client/lang/MekanismLangProvider.java
> +        add(MekanismLang.ISSUE_REDSTONE_UNACTIVATED, " - Inactive because of the redstone control setting");
Sure, we'll go with those.

2024-12-02 11:24 UTC, bukowski912 commented
Note that the special blending technique used for the warning overlay may have performance drawbacks, especially in light of previous optimization (e.g. 609b030). In addition, I renamed `GuiSideHolder#draw()` to `drawHolder()` as I thought that was much clearer. Let me know if that was an overstep.

2024-12-20 11:55 UTC, thiakil commented
>  In addition, I renamed GuiSideHolder#draw() to drawHolder() as I thought that was much clearer. Let me know if that was an overstep.

I'd rather that be in a separate PR, just to avoid the noise it creates in the diffs

2025-01-30 00:40 UTC, pupnewfster requested changes

2025-01-30 00:40 UTC, pupnewfster commented on src/main/java/mekanism/common/tile/base/TileEntityMekanism.java
> +            container.track(SyncableBoolean.create(this::isPowered, value -> redstone = value));
Do we also need to sync `redstoneLastTick`?

2025-01-30 00:40 UTC, pupnewfster commented on src/main/java/mekanism/client/gui/GuiMekanismTile.java
> +                .warning(WarningType.REDSTONE_PULSE_REQUIRED, () -> !tile.isRedstoneActivated() && tile.getControlType() == RedstoneControl.PULSE));
Can you switch the order of these so it checks the control type matches before checking if it isn't activated?

2025-01-30 14:02 UTC, pupnewfster approved these changes

2025-01-30 14:03 UTC, merged